### ISSUE TITLE
Add viewport size viewing option

### ISSUE THREAD

**Issue by Kurzdor** [ssimplix/resolith#4]
Hi.
I found a link to this app in Telegram.
App is good, but it could be more better if you add show viewport size option.
Because the viewport more important than what is my screen resolution.

**Comment by ssimplix** [comment]
Hi!

Yeah, I've planned this before. It will be added soon.

**Comment by Kurzdor** [comment]
Thx!

**Comment by ssimplix** [comment]
Implemented with https://github.com/ssimplix/resolith/commit/32765a60e52f559e1fb4326d0784e8ae26eb05eb.
